services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: book_circle
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  web:
    build: ./backend
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 book_circle.wsgi:application"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    environment:
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      DEBUG: ${DEBUG}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_API_AUDIENCE: ${AUTH0_API_AUDIENCE}
      AUTH0_ALGORITHMS: ${AUTH0_ALGORITHMS}
    depends_on:
      - db
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
    enable_ipv6: false
