# Generated by Django 5.2.4 on 2025-09-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_publication_year_book_cover_image'),
        ('users', '0003_remove_userprofile_user_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='users.userprofile'),
        ),
    ]
