# Generated by Django 5.2.4 on 2025-09-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Excellent'), (2, 'Fair')], default=2),
        ),
    ]
